import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./redux/providers";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={inter.className}
      >

      
        <Providers>
          {
            children
          }
        </Providers>
      
      </body>
    </html>
  );
}
